// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for SearchChunkParamsKind.
const (
	Body       SearchChunkParamsKind = "body"
	Caption    SearchChunkParamsKind = "caption"
	Ocr        SearchChunkParamsKind = "ocr"
	Summary    SearchChunkParamsKind = "summary"
	Transcript SearchChunkParamsKind = "transcript"
)

// AgentInvocation defines model for AgentInvocation.
type AgentInvocation struct {
	Arguments map[string]interface{} `json:"arguments"`
	Name      string                 `json:"name"`
}

// AgentToolsResponse defines model for AgentToolsResponse.
type AgentToolsResponse struct {
	Tools *[]map[string]interface{} `json:"tools,omitempty"`
}

// ChunkContextResponse defines model for ChunkContextResponse.
type ChunkContextResponse struct {
	AnchorChunkNo *int `json:"anchor_chunk_no,omitempty"`
	Chunks        *[]struct {
		ChunkNo     *int    `json:"chunk_no,omitempty"`
		OffsetEnd   *int    `json:"offset_end"`
		OffsetStart *int    `json:"offset_start"`
		Page        *int    `json:"page"`
		Text        *string `json:"text,omitempty"`
	} `json:"chunks,omitempty"`
	FileId *string `json:"file_id,omitempty"`
	Kind   *string `json:"kind,omitempty"`
}

// Cite defines model for Cite.
type Cite struct {
	ChunkNo      *int `json:"chunk_no,omitempty"`
	FrameMsEnd   *int `json:"frame_ms_end"`
	FrameMsStart *int `json:"frame_ms_start"`
	OffsetEnd    *int `json:"offset_end"`
	OffsetStart  *int `json:"offset_start"`
	Page         *int `json:"page"`
}

// FileChunksResponse defines model for FileChunksResponse.
type FileChunksResponse struct {
	Chunks *[]struct {
		ChunkNo      *int    `json:"chunk_no,omitempty"`
		FrameMsEnd   *int    `json:"frame_ms_end"`
		FrameMsStart *int    `json:"frame_ms_start"`
		Kind         *string `json:"kind,omitempty"`
		OffsetEnd    *int    `json:"offset_end"`
		OffsetStart  *int    `json:"offset_start"`
		Page         *int    `json:"page"`
		Text         *string `json:"text,omitempty"`
	} `json:"chunks,omitempty"`
	FileId *string `json:"file_id,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
	Offset *int    `json:"offset,omitempty"`
	Total  *int    `json:"total,omitempty"`
}

// FileGroup defines model for FileGroup.
type FileGroup struct {
	Chunks *[]Hit  `json:"chunks,omitempty"`
	FileId *string `json:"file_id,omitempty"`
	Kind   *string `json:"kind,omitempty"`
	Mime   *string `json:"mime,omitempty"`
	Paths  *[]struct {
		Path   *string `json:"path,omitempty"`
		RootId *string `json:"root_id,omitempty"`
	} `json:"paths,omitempty"`
	Score *float32 `json:"score,omitempty"`
}

// Filters defines model for Filters.
type Filters struct {
	KindIn *[]string `json:"kind_in,omitempty"`
	LangIn *[]string `json:"lang_in,omitempty"`

	// MimePrefix Mime filter. An entry ending in "/" is a prefix and selects every mime currently present in the index that starts with it (e.g. "text/", "text/markdown+docling/"). Any other entry is an exact mime, so "text/markdown" does NOT also select "text/markdown+docling/pdf". An empty match set yields zero hits. If the mime facet is unavailable the raw list is applied as exact values and the response carries the warning "mime_facet_unavailable".
	MimePrefix *[]string `json:"mime_prefix,omitempty"`
	RootIds    *[]string `json:"root_ids,omitempty"`
}

// Hit defines model for Hit.
type Hit struct {
	Cite       *Cite   `json:"cite,omitempty"`
	Collection *string `json:"collection,omitempty"`
	FileId     *string `json:"file_id,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	Mime       *string `json:"mime,omitempty"`
	Paths      *[]struct {
		Path   *string `json:"path,omitempty"`
		RootId *string `json:"root_id,omitempty"`
	} `json:"paths,omitempty"`
	PayloadExtra *map[string]interface{} `json:"payload_extra,omitempty"`
	Preview      *struct {
		Text         *string `json:"text"`
		ThumbnailUrl *string `json:"thumbnail_url"`
	} `json:"preview,omitempty"`
	RawScore *float32 `json:"raw_score,omitempty"`
	Score    *float32 `json:"score,omitempty"`
}

// ImageHit One image candidate returned by the visual search proxy
type ImageHit struct {
	// AssetId Unique identifier in NimoOS-Photos
	AssetId *string `json:"asset_id,omitempty"`

	// Name Original filename of the image
	Name *string `json:"name,omitempty"`

	// Path Absolute path on the NAS
	Path *string `json:"path,omitempty"`

	// Score Similarity score from Photos smart-search (0–1)
	Score *float32 `json:"score,omitempty"`

	// TakenAt ISO-8601 timestamp when the photo was taken (omitted if unknown)
	TakenAt *string `json:"taken_at"`

	// ThumbnailUrl Relative URL to the small thumbnail, e.g. /v1/photos/assets/{id}/thumbnail?size=small
	ThumbnailUrl *string `json:"thumbnail_url,omitempty"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Filters          *Filters `json:"filters,omitempty"`
	GroupByFile      *bool    `json:"group_by_file,omitempty"`
	IncludeNeighbors *bool    `json:"include_neighbors,omitempty"`
	MaxChunksPerFile *int     `json:"max_chunks_per_file,omitempty"`
	Query            string   `json:"query"`
	Rerank           *bool    `json:"rerank,omitempty"`
	TopK             *int     `json:"top_k,omitempty"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Files *[]FileGroup `json:"files,omitempty"`
	Hits  *[]Hit       `json:"hits,omitempty"`
	Stats *struct {
		EmbedMs         *int `json:"embed_ms,omitempty"`
		ExpandMs        *int `json:"expand_ms,omitempty"`
		RerankMs        *int `json:"rerank_ms,omitempty"`
		TotalCandidates *int `json:"total_candidates,omitempty"`
		VectorSearchMs  *int `json:"vector_search_ms,omitempty"`
	} `json:"stats,omitempty"`
	Warnings *[]string `json:"warnings,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Error *string `json:"error,omitempty"`
}

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable struct {
	Detail     *string `json:"detail"`
	Error      *string `json:"error,omitempty"`
	RetryAfter *int    `json:"retry_after"`
}

// SearchChunkParams defines parameters for SearchChunk.
type SearchChunkParams struct {
	FileId  string                `form:"file_id" json:"file_id"`
	Kind    SearchChunkParamsKind `form:"kind" json:"kind"`
	ChunkNo int                   `form:"chunk_no" json:"chunk_no"`
	Window  *int                  `form:"window,omitempty" json:"window,omitempty"`
}

// SearchChunkParamsKind defines parameters for SearchChunk.
type SearchChunkParamsKind string

// SearchFileParams defines parameters for SearchFile.
type SearchFileParams struct {
	FileId string `form:"file_id" json:"file_id"`
	Offset *int   `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// SearchVisualJSONBody defines parameters for SearchVisual.
type SearchVisualJSONBody struct {
	// Query Natural-language image search query
	Query string `json:"query"`

	// TopK Maximum number of image hits to return
	TopK *int `json:"top_k,omitempty"`
}

// AgentToolInvokeJSONRequestBody defines body for AgentToolInvoke for application/json ContentType.
type AgentToolInvokeJSONRequestBody = AgentInvocation

// SearchTextJSONRequestBody defines body for SearchText for application/json ContentType.
type SearchTextJSONRequestBody = SearchRequest

// SearchVisualJSONRequestBody defines body for SearchVisual for application/json ContentType.
type SearchVisualJSONRequestBody SearchVisualJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Upstream connectivity check (localhost-only)
	// (GET /_internal/health)
	InternalHealth(ctx echo.Context) error
	// KPI snapshot (localhost-only)
	// (GET /_internal/stats)
	InternalStats(ctx echo.Context) error
	// Warm up BGE-M3 + cache
	// (POST /_internal/warm)
	InternalWarm(ctx echo.Context) error
	// Filter field documentation for the agent
	// (GET /agent/filters-schema)
	AgentFiltersSchema(ctx echo.Context) error
	// Unified tool dispatch (nimoos_search / read_file_chunk)
	// (POST /agent/tool)
	AgentToolInvoke(ctx echo.Context) error
	// Return OpenAI function-calling schema for agent tools
	// (GET /agent/tools)
	AgentTools(ctx echo.Context) error
	// Fetch anchor chunk plus neighbor window
	// (GET /chunk)
	SearchChunk(ctx echo.Context, params SearchChunkParams) error
	// List all chunks of a file (paginated)
	// (GET /file)
	SearchFile(ctx echo.Context, params SearchFileParams) error
	// Hybrid retrieval (NOT YET IMPLEMENTED in MVP — returns 503)
	// (POST /hybrid)
	SearchHybrid(ctx echo.Context) error
	// Text retrieval (BGE-M3 dense + sparse + rerank)
	// (POST /text)
	SearchText(ctx echo.Context) error
	// Thumbnail (NOT YET IMPLEMENTED in MVP — returns 404)
	// (GET /thumb/{file_id})
	SearchThumb(ctx echo.Context, fileId string) error
	// Image search via Photos service (returns 503 when Photos unavailable)
	// (POST /visual)
	SearchVisual(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// InternalHealth converts echo context to params.
func (w *ServerInterfaceWrapper) InternalHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InternalHealth(ctx)
	return err
}

// InternalStats converts echo context to params.
func (w *ServerInterfaceWrapper) InternalStats(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InternalStats(ctx)
	return err
}

// InternalWarm converts echo context to params.
func (w *ServerInterfaceWrapper) InternalWarm(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InternalWarm(ctx)
	return err
}

// AgentFiltersSchema converts echo context to params.
func (w *ServerInterfaceWrapper) AgentFiltersSchema(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AgentFiltersSchema(ctx)
	return err
}

// AgentToolInvoke converts echo context to params.
func (w *ServerInterfaceWrapper) AgentToolInvoke(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AgentToolInvoke(ctx)
	return err
}

// AgentTools converts echo context to params.
func (w *ServerInterfaceWrapper) AgentTools(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AgentTools(ctx)
	return err
}

// SearchChunk converts echo context to params.
func (w *ServerInterfaceWrapper) SearchChunk(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchChunkParams
	// ------------- Required query parameter "file_id" -------------

	err = runtime.BindQueryParameter("form", true, true, "file_id", ctx.QueryParams(), &params.FileId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter file_id: %s", err))
	}

	// ------------- Required query parameter "kind" -------------

	err = runtime.BindQueryParameter("form", true, true, "kind", ctx.QueryParams(), &params.Kind)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter kind: %s", err))
	}

	// ------------- Required query parameter "chunk_no" -------------

	err = runtime.BindQueryParameter("form", true, true, "chunk_no", ctx.QueryParams(), &params.ChunkNo)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter chunk_no: %s", err))
	}

	// ------------- Optional query parameter "window" -------------

	err = runtime.BindQueryParameter("form", true, false, "window", ctx.QueryParams(), &params.Window)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter window: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SearchChunk(ctx, params)
	return err
}

// SearchFile converts echo context to params.
func (w *ServerInterfaceWrapper) SearchFile(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchFileParams
	// ------------- Required query parameter "file_id" -------------

	err = runtime.BindQueryParameter("form", true, true, "file_id", ctx.QueryParams(), &params.FileId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter file_id: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SearchFile(ctx, params)
	return err
}

// SearchHybrid converts echo context to params.
func (w *ServerInterfaceWrapper) SearchHybrid(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SearchHybrid(ctx)
	return err
}

// SearchText converts echo context to params.
func (w *ServerInterfaceWrapper) SearchText(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SearchText(ctx)
	return err
}

// SearchThumb converts echo context to params.
func (w *ServerInterfaceWrapper) SearchThumb(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "file_id" -------------
	var fileId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "file_id", runtime.ParamLocationPath, ctx.Param("file_id"), &fileId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter file_id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SearchThumb(ctx, fileId)
	return err
}

// SearchVisual converts echo context to params.
func (w *ServerInterfaceWrapper) SearchVisual(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SearchVisual(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/_internal/health", wrapper.InternalHealth)
	router.GET(baseURL+"/_internal/stats", wrapper.InternalStats)
	router.POST(baseURL+"/_internal/warm", wrapper.InternalWarm)
	router.GET(baseURL+"/agent/filters-schema", wrapper.AgentFiltersSchema)
	router.POST(baseURL+"/agent/tool", wrapper.AgentToolInvoke)
	router.GET(baseURL+"/agent/tools", wrapper.AgentTools)
	router.GET(baseURL+"/chunk", wrapper.SearchChunk)
	router.GET(baseURL+"/file", wrapper.SearchFile)
	router.POST(baseURL+"/hybrid", wrapper.SearchHybrid)
	router.POST(baseURL+"/text", wrapper.SearchText)
	router.GET(baseURL+"/thumb/:file_id", wrapper.SearchThumb)
	router.POST(baseURL+"/visual", wrapper.SearchVisual)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RabW/bOPL/KgP+/y8SVI6ctFkcAhwOaa/bGtsmRZLu4dAUAi2NLW4oUiVHdtzCwH6H",
	"u0+4n+RAUn4M7ThNWyzu3inWcDgPv3lUvrBcV7VWqMiyky/MoK21suj/eM6LC/zUoCX3V64VofKPvK6l",
	"yDkJrdLfrFbuN5uXWHH3VBtdoyERmKAx2rgHmtTITpglI9SQTafJ7Bfd/w1zYlP3U4E2N6J2nNmJEwBM",
	"K8E0YZdoRiLH94qPuJC8L/ERchVIXEj3pBrZMiPTYLIuaLJRhYQZJDPJ+IDQbOEkFOEQzW46v68tGeQV",
	"NAs1IQWlCURVS6xQERaeV1DNa3M6REU9NdJB+7vqcjNsqpmX14RImOIVxn3kzC8MFuzkQ6BKllh9TO6y",
	"8pJcaS3tRYulu8KQe+0eBGEVl6j9gRvDJzHDJexF2aibF875t7T5Kq7yUpssd8SZ0kt3zb2SMP92VaBV",
	"LtuP68HAImWoil1AMKe3xA3tdqLmQ9yN0lljp2hbN3HCBkJiJooo0G+EKnZk+0IQPtSCA8MrzCq7uw3n",
	"Jx5gxT+Pn2J2+1lI9JjeEjiPBOqPMfMGrPxPxIkUlaBtWSL+jjRxGXu1CSivjG7qnfDx/wYH7IT9X7oo",
	"9GlbONLX4lslgoRVIlpCnE+o3AZZ9z5eXLWmuBi7eMnm2iwLpJqqv8WihCYim9M2EypWqhZyrt8suRo+",
	"+JAzX1YbHIjb0J0s9wRvRYUw8EIewKkCVGQmgKoQaghCwTVLrxkICxwCC+CqAIsSc7KAIzQTcBdA3hiD",
	"iuTE0VlU5E5TiSBUgbdAJSfw4WZhLKgEQbCHB8MDuPYBk16zZPZYcXNT6LF6UuhcCjVMr9m+E24Cmko0",
	"rYxOJgV4y3PyEiRg9TqHawaFRgtn51fApdWt4BsvqovBNQt2qGqaQMUpL8EiwUSgLCx8RqOhFGQPoDfw",
	"6nnlBzxHchItd1bureFjkML6d76FxAK4baUecdmg9Qb1tG1uhpwbI9D6H8fcKOeK6+BGf1G2dMs1O2DJ",
	"A8DQIt8+BEIxXL8OuWgtR7T1eVti8DXcNUZaOle0HeUdCf4rEkXNJ1LzIsNbMjzai9YGRwLHkT62LSL3",
	"ThBUNlVfcSGzxuwyc8TkNnycbUpqD0t3vYoPscXGaqI5VwjCvYWcq0IUnBziqTEKC+hPPNhHwjZcgkVu",
	"8hJqo28nLFnvuq0r3MEla+ONEp8aBFGgIjEQaFwGOhOVPr/svCs1acsi9pvNJ2vSGjEUikuXGtGRgA7h",
	"7lWI8ZlBaJXPad9q2RCCew06ZMSz08sYh7mdV1lcikpIbgRNwFPAwOgKgkJgK26o0xpsr/vH7/863F/w",
	"XviQ+A2qjEf80rs87/zlp+4hkKjQEq9qGJcYBK3dJTDmFvx52NOVIMICxAAadaP0WLnbHo7RVREuUHIS",
	"I4T3F2+AtL/aVlxKmB9MwNeKdHSYeqFs6nFg0y+imKZzsr9Z8Rn/6s+ynZB/6S23tIpYBdtgUb235bRZ",
	"kZ8mbOi6p6w/yRxwgqoD3khiJwMu7cI4fa0lcuWOCJXLpsBMoRiWfW3sbscqfhtmT5vVaO7ed+xJRNVU",
	"7OSoG2tUPzVoJhuWD4armxV2K65dEoN0na1SusvmNx92u9EZZXn4D3J83OKeTUOLU3r3nnTR3UZytSvq",
	"j+1uLXGKVBes+lhkK6V2yQt4W3O1+XVwxcbXvr3P5il1A9UIc9ImC3liA69YeLTdxyO7hakH+UDHIp+M",
	"wBGXcPquBwNt2nwNF6evQPKJa0ovEaFAK4YKbI05HHWPfup0jztHRx0lKq1tm/46geigKlzoC3LhwNr0",
	"H3DkLmHOGMaG67sHhwddP0DVqHgt2Al7etA9eMqWOoY0cxYyisu0RC5Dkh+Gacs52S/FeoXLpC3d60CW",
	"rG48j7rdSJn5JWzbmqriLhQXK7pcK+Xao5HL+3mJ+Q3sSZ1zWWpLHa3kZN8fXRJvjr6t0l16qq8S7pd3",
	"PbCK17bUdK80Y24qHwrabpHmH47qq4RxJ6Gp4fmrl523T+EJ5DwvMUjBh6gobZN3Z7GmjRrGbxXbDH4Z",
	"SOMC7bwNvncRe0eZcD0M3JABhc79EtSz90HhCqLXaVk90lpuNvB8V9pTI32DLGRctPRcF5MHabMtD67v",
	"hqerqd3VjOmPMGbCngW2MWHn16dLXx3Wwk65hrEAZ1MohK393LcX8kubNiEFg7zwhTYU3v11d9jtIPOr",
	"68eC6153rC7Id0HfhW/D4bxGddqDQaP8WNbJuXRDMQTuHoheVQiqet29HTZqHdKu3zz6lGp4haGf+vCF",
	"CSdLKP2zLnw+9a2DKLkLiEVXF2flh8RtfFC5/uQD67uASJjODUtYzoOVEkaGq2A1trDVx2TX6+fb0h1U",
	"WSrBcWZjoQo9ZstHF93WUrN1HGm1Pn5HvEW/k2wJ0Wd38/qZJvhZN6pYz4joIjB8YgFvTKhlY2HWJENr",
	"E4/CWe+7BYSu9/vhGGz3slG/RdviOJuw+Y1yOe6udPndHwyAyIeFr3Q/7ClNwBsqtRGfsYDzi/BhUhV4",
	"i8X+GjzeCEvgJsQwAbnpnPtZHfZq7iZ3mp1Jy0nfhHVBvFIGfLwOVGu2Ou4+vb+qRL4drwobeIOZN7t7",
	"Z+dX8M+XV9B7++7Ny7cvz65e/h2Egre/voM/fv93uxexcNx92ioxWwdtU+HK0XyfOr86Jn+HKr/L5fcD",
	"7IEtQPKN/OsMv+zdtiUtUFmEJ2BrbvxDGOVmHi2bqp9+abPN9J70deWoN+Qvv3l6VPpaTxEbQ7W3+DeB",
	"Fq/rpphtYnbG+LPus9YiYft3H8p/DVRfj/PV2Xy+A1lTllNjuOxIroYNH85Wl20nOMvPdyfh6DJk7YtL",
	"SNcQlnMucwXepSALpFvDsG+0Q/n2obpqPy/77ouT+X54x7XBnyrOe8sYGAk+X8KGg7C3lLfDErUlWPpe",
	"sx/0ckdmQex3oqwkqk/SdD5Vp6PDNFzFph+n/wkAAP//DTNRhk0lAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
