// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for SearchChunkParamsKind.
const (
	Body       SearchChunkParamsKind = "body"
	Caption    SearchChunkParamsKind = "caption"
	Ocr        SearchChunkParamsKind = "ocr"
	Summary    SearchChunkParamsKind = "summary"
	Transcript SearchChunkParamsKind = "transcript"
)

// AgentInvocation defines model for AgentInvocation.
type AgentInvocation struct {
	Arguments map[string]interface{} `json:"arguments"`
	Name      string                 `json:"name"`
}

// AgentToolsResponse defines model for AgentToolsResponse.
type AgentToolsResponse struct {
	Tools *[]map[string]interface{} `json:"tools,omitempty"`
}

// ChunkContextResponse defines model for ChunkContextResponse.
type ChunkContextResponse struct {
	AnchorChunkNo *int `json:"anchor_chunk_no,omitempty"`
	Chunks        *[]struct {
		ChunkNo     *int    `json:"chunk_no,omitempty"`
		OffsetEnd   *int    `json:"offset_end"`
		OffsetStart *int    `json:"offset_start"`
		Page        *int    `json:"page"`
		Text        *string `json:"text,omitempty"`
	} `json:"chunks,omitempty"`
	FileId *string `json:"file_id,omitempty"`
	Kind   *string `json:"kind,omitempty"`
}

// Cite defines model for Cite.
type Cite struct {
	ChunkNo      *int `json:"chunk_no,omitempty"`
	FrameMsEnd   *int `json:"frame_ms_end"`
	FrameMsStart *int `json:"frame_ms_start"`
	OffsetEnd    *int `json:"offset_end"`
	OffsetStart  *int `json:"offset_start"`
	Page         *int `json:"page"`
}

// FileChunksResponse defines model for FileChunksResponse.
type FileChunksResponse struct {
	Chunks *[]struct {
		ChunkNo      *int    `json:"chunk_no,omitempty"`
		FrameMsEnd   *int    `json:"frame_ms_end"`
		FrameMsStart *int    `json:"frame_ms_start"`
		Kind         *string `json:"kind,omitempty"`
		OffsetEnd    *int    `json:"offset_end"`
		OffsetStart  *int    `json:"offset_start"`
		Page         *int    `json:"page"`
		Text         *string `json:"text,omitempty"`
	} `json:"chunks,omitempty"`
	FileId *string `json:"file_id,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
	Offset *int    `json:"offset,omitempty"`
	Total  *int    `json:"total,omitempty"`
}

// Filters defines model for Filters.
type Filters struct {
	KindIn     *[]string `json:"kind_in,omitempty"`
	LangIn     *[]string `json:"lang_in,omitempty"`
	MimePrefix *[]string `json:"mime_prefix,omitempty"`
	RootIds    *[]string `json:"root_ids,omitempty"`
}

// Hit defines model for Hit.
type Hit struct {
	Cite       *Cite   `json:"cite,omitempty"`
	Collection *string `json:"collection,omitempty"`
	FileId     *string `json:"file_id,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	Mime       *string `json:"mime,omitempty"`
	Paths      *[]struct {
		Path   *string `json:"path,omitempty"`
		RootId *string `json:"root_id,omitempty"`
	} `json:"paths,omitempty"`
	PayloadExtra *map[string]interface{} `json:"payload_extra,omitempty"`
	Preview      *struct {
		Text         *string `json:"text"`
		ThumbnailUrl *string `json:"thumbnail_url"`
	} `json:"preview,omitempty"`
	RawScore *float32 `json:"raw_score,omitempty"`
	Score    *float32 `json:"score,omitempty"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Filters          *Filters `json:"filters,omitempty"`
	IncludeNeighbors *bool    `json:"include_neighbors,omitempty"`
	Query            string   `json:"query"`
	Rerank           *bool    `json:"rerank,omitempty"`
	TopK             *int     `json:"top_k,omitempty"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Hits  *[]Hit `json:"hits,omitempty"`
	Stats *struct {
		EmbedMs         *int `json:"embed_ms,omitempty"`
		ExpandMs        *int `json:"expand_ms,omitempty"`
		RerankMs        *int `json:"rerank_ms,omitempty"`
		TotalCandidates *int `json:"total_candidates,omitempty"`
		VectorSearchMs  *int `json:"vector_search_ms,omitempty"`
	} `json:"stats,omitempty"`
	Warnings *[]string `json:"warnings,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Error *string `json:"error,omitempty"`
}

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable struct {
	Detail     *string `json:"detail"`
	Error      *string `json:"error,omitempty"`
	RetryAfter *int    `json:"retry_after"`
}

// SearchChunkParams defines parameters for SearchChunk.
type SearchChunkParams struct {
	FileId  string                `form:"file_id" json:"file_id"`
	Kind    SearchChunkParamsKind `form:"kind" json:"kind"`
	ChunkNo int                   `form:"chunk_no" json:"chunk_no"`
	Window  *int                  `form:"window,omitempty" json:"window,omitempty"`
}

// SearchChunkParamsKind defines parameters for SearchChunk.
type SearchChunkParamsKind string

// SearchFileParams defines parameters for SearchFile.
type SearchFileParams struct {
	FileId string `form:"file_id" json:"file_id"`
	Offset *int   `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// AgentToolInvokeJSONRequestBody defines body for AgentToolInvoke for application/json ContentType.
type AgentToolInvokeJSONRequestBody = AgentInvocation

// SearchTextJSONRequestBody defines body for SearchText for application/json ContentType.
type SearchTextJSONRequestBody = SearchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Upstream connectivity check (localhost-only)
	// (GET /_internal/health)
	InternalHealth(ctx echo.Context) error
	// KPI snapshot (localhost-only)
	// (GET /_internal/stats)
	InternalStats(ctx echo.Context) error
	// Warm up BGE-M3 + cache
	// (POST /_internal/warm)
	InternalWarm(ctx echo.Context) error
	// Filter field documentation for the agent
	// (GET /agent/filters-schema)
	AgentFiltersSchema(ctx echo.Context) error
	// Unified tool dispatch (nimoos_search / read_file_chunk)
	// (POST /agent/tool)
	AgentToolInvoke(ctx echo.Context) error
	// Return OpenAI function-calling schema for agent tools
	// (GET /agent/tools)
	AgentTools(ctx echo.Context) error
	// Fetch anchor chunk plus neighbor window
	// (GET /chunk)
	SearchChunk(ctx echo.Context, params SearchChunkParams) error
	// List all chunks of a file (paginated)
	// (GET /file)
	SearchFile(ctx echo.Context, params SearchFileParams) error
	// Hybrid retrieval (NOT YET IMPLEMENTED in MVP — returns 503)
	// (POST /hybrid)
	SearchHybrid(ctx echo.Context) error
	// Text retrieval (BGE-M3 dense + sparse + rerank)
	// (POST /text)
	SearchText(ctx echo.Context) error
	// Thumbnail (NOT YET IMPLEMENTED in MVP — returns 404)
	// (GET /thumb/{file_id})
	SearchThumb(ctx echo.Context, fileId string) error
	// Visual retrieval (NOT YET IMPLEMENTED in MVP — returns 503)
	// (POST /visual)
	SearchVisual(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// InternalHealth converts echo context to params.
func (w *ServerInterfaceWrapper) InternalHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InternalHealth(ctx)
	return err
}

// InternalStats converts echo context to params.
func (w *ServerInterfaceWrapper) InternalStats(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InternalStats(ctx)
	return err
}

// InternalWarm converts echo context to params.
func (w *ServerInterfaceWrapper) InternalWarm(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InternalWarm(ctx)
	return err
}

// AgentFiltersSchema converts echo context to params.
func (w *ServerInterfaceWrapper) AgentFiltersSchema(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AgentFiltersSchema(ctx)
	return err
}

// AgentToolInvoke converts echo context to params.
func (w *ServerInterfaceWrapper) AgentToolInvoke(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AgentToolInvoke(ctx)
	return err
}

// AgentTools converts echo context to params.
func (w *ServerInterfaceWrapper) AgentTools(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AgentTools(ctx)
	return err
}

// SearchChunk converts echo context to params.
func (w *ServerInterfaceWrapper) SearchChunk(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchChunkParams
	// ------------- Required query parameter "file_id" -------------

	err = runtime.BindQueryParameter("form", true, true, "file_id", ctx.QueryParams(), &params.FileId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter file_id: %s", err))
	}

	// ------------- Required query parameter "kind" -------------

	err = runtime.BindQueryParameter("form", true, true, "kind", ctx.QueryParams(), &params.Kind)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter kind: %s", err))
	}

	// ------------- Required query parameter "chunk_no" -------------

	err = runtime.BindQueryParameter("form", true, true, "chunk_no", ctx.QueryParams(), &params.ChunkNo)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter chunk_no: %s", err))
	}

	// ------------- Optional query parameter "window" -------------

	err = runtime.BindQueryParameter("form", true, false, "window", ctx.QueryParams(), &params.Window)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter window: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SearchChunk(ctx, params)
	return err
}

// SearchFile converts echo context to params.
func (w *ServerInterfaceWrapper) SearchFile(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchFileParams
	// ------------- Required query parameter "file_id" -------------

	err = runtime.BindQueryParameter("form", true, true, "file_id", ctx.QueryParams(), &params.FileId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter file_id: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SearchFile(ctx, params)
	return err
}

// SearchHybrid converts echo context to params.
func (w *ServerInterfaceWrapper) SearchHybrid(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SearchHybrid(ctx)
	return err
}

// SearchText converts echo context to params.
func (w *ServerInterfaceWrapper) SearchText(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SearchText(ctx)
	return err
}

// SearchThumb converts echo context to params.
func (w *ServerInterfaceWrapper) SearchThumb(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "file_id" -------------
	var fileId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "file_id", runtime.ParamLocationPath, ctx.Param("file_id"), &fileId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter file_id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SearchThumb(ctx, fileId)
	return err
}

// SearchVisual converts echo context to params.
func (w *ServerInterfaceWrapper) SearchVisual(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SearchVisual(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/_internal/health", wrapper.InternalHealth)
	router.GET(baseURL+"/_internal/stats", wrapper.InternalStats)
	router.POST(baseURL+"/_internal/warm", wrapper.InternalWarm)
	router.GET(baseURL+"/agent/filters-schema", wrapper.AgentFiltersSchema)
	router.POST(baseURL+"/agent/tool", wrapper.AgentToolInvoke)
	router.GET(baseURL+"/agent/tools", wrapper.AgentTools)
	router.GET(baseURL+"/chunk", wrapper.SearchChunk)
	router.GET(baseURL+"/file", wrapper.SearchFile)
	router.POST(baseURL+"/hybrid", wrapper.SearchHybrid)
	router.POST(baseURL+"/text", wrapper.SearchText)
	router.GET(baseURL+"/thumb/:file_id", wrapper.SearchThumb)
	router.POST(baseURL+"/visual", wrapper.SearchVisual)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RZ227bPBJ+FYK7FykqR24Oe+G7tJu2RpsDkrSLRREIY2lksaFIlaSceAMD+xD7hPsk",
	"C5KyLdv0Icmm+IH/TjGHw5lvvhnOMI80lWUlBQqjae+RKtSVFBrdH+8hu8JfNWpj/0qlMCjcJ1QVZykY",
	"JkX8U0thf9NpgSXYr0rJCpVhXgkqJZX9MOMKaY9qo5gY0skkmv4iBz8xNXRif8pQp4pVVjPtWQOIaiyY",
	"RPQa1Yil+E3ACBiHAccX2JWhAcbtl6h5o8yoGqNlQ6O1LkRUoVHjBHKDaoMmJgwOUe3m87dKG4VQknru",
	"JomJkIawsuJYojCYOV3eNefNyRCF6YuR9N6vugtqWJfTKC8ZEVEBJYZjZOFnCjPa++Glopaq22hVlbPk",
	"RkqurxourRpj7LL9YAbLsEXND6AUjEPARfRDUYu7Dzb4D2b9USDSQqoktcKJkK2zZlGJqFtdNGhRy+bt",
	"Ms81mgRFtgsJZvLagDK77ahgiLtJWjR2yrZliCOaM44Jy4JEv2Mi21HtB2bwqQjmCkpMSr07hrMdT0Dx",
	"jxOnEG4fGUfH6Q2J80Ki/h6Y13DlT5EnnJXMbKoS4TUjDfDQ0hqiGFSB4FvgEyZChXVu4bI3HMTwyZtK",
	"VmJSKczZw9M2KilNwjL9lF0hDD57lJfI31SevyrMaY/+JZ73NnFzV8auOtmSLznHdHpXrljwjFroUQku",
	"VGCKTVlr18P9hYfrmUStYMwlZAk+GAXBW7ZSOGJ4H7ihm/TY2huZoi4HAhhParVLNxWyW8F9olOp2uCJ",
	"uhz43Fi3EtJ0jaDSotW0LnqVzzNnE0emCTaJKBMprzNMBLJhMZCqaR1zqLmhvRy4nrs4kJIjCLvtV41q",
	"vKZjVCDuFrQs4NRSYmSVLEoedCNawgMr65L23nW7wYul3bF5O243ILXupimYWWTsJsBsNgb4pw2YANux",
	"HGCWLKR+qxTiQwVi/bLHb+2yK6RJCiJjGRhcIzXC1EiVaIfBGl0het2DEkwMX1i9Jo5XufShbff+V2gU",
	"wxFwcnLZJ7lU5JyV8uKaXJ18IhzGqPbJNSLJULOhILrClBx0D/7W6R53Dg46gpVS6o53q+OF9suMRtQw",
	"YzOSenUdH3x7CLVgKO2P7+6/2++6q6pCARWjPXq4390/pK0KFicWISWAxwUC93Vr6O81G2Q3fvQz2qP9",
	"Ru6zF4sWZ8uDbnfV/4svfq6pyxJs/syHoVQKYcv1iJkxSQtM78gelynwQmrTkYKP37itLfNm7Nto3bWT",
	"epZxXy77RAuodCHNVmvuQZUuFaTeYM0/rNSzjLE7SV2R959OO2eH5C1JIS3QWwF2JIub4teZD8RBYNz8",
	"1lTAay8aNmjnuXvryLvijD+e5Ax5RjKZunHTqXdJYQokzqe2e3amXA/wbCq1M/IdUl8mUZv3Mhs/yZtN",
	"dXB5Cp8s1mNb6Ce/A8yIHnm1IWNnx8et952ltBMsZ5gRiynJmK7ApAXZ8/WlKZskJgohS1yn5MaON8vh",
	"0JtJ5h4JXkqureFYfIrYhX1XaGolyEWF4qRP8lq4NrGTAudMDInX7ojoXCXeVee7w2Gt177suhnPlVQ7",
	"W/l+5McjtS14c19P32NmXegyiaJVQsz7q7Aq17Ru0oPCNhU/6MAmRERlqmhEU/AoRdQoEB41OsfqNtr1",
	"+NlcuoMrrSs4rOyeiUze0/bWeYvU6pCOA/3R7SvyLfgitSFFj1br+rk05KOsRbZcEdFmoH/MIg5MUvFa",
	"k2lfShpMHAstbbaQ8KMV+d0cbCbgYNyCvWxYjZ+xg1qO2w3yQbBBfk0CBJ5wnhl+siekIVCbQir2L8zI",
	"xZV/AhYZPmD2ZokeX5k2BDj31NBE5gSIjRzZq2DIBJjpnrgYD5SfKMM3pefHZy+1hNVx93D7rRJ4pV80",
	"1usmatbs7p1f3JB/nt6Q/tnl19Oz0/Ob078TJsjZ90vy33//x0rWSmhy3D1snJiOp5tcuLEyr3PPL46Z",
	"r3DL73L4doI9sQWI/k/xtcC3o9u0pBkKjeQt0RUo9+FHuWlEi7ocxI9NtZlsKV83VnpN/XKPKS8qX8sl",
	"Ym2q9uf/kGn4ugzF9HVkZ44fdY8aREZM18C3sfy7l3qVRPW6n5+oVhmq0TQ67oGIFsZUvTiejUvx6F3s",
	"O0o6uZ38LwAA//+JAiFGkBwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
